name: solar system workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "Feature/*"

env:
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: unit testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18, 19, 20]
        exclude:
          - os: macos-latest
            node-version: 19

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install depend.
        run: npm install

      - name: unit testing
        id: nodejs-unit-testing-step
        run: npm test

      - name: archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results ${{ matrix.os }}-${{ matrix.node-version }}
          path: test-results.xml
          retention-days: 1

  code-coverage:
    name: code coverage
    runs-on: ubuntu-latest
    # needs:
    #   - unit-testing

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install depend.
        run: npm install

      - name: check code coverge
        continue-on-error: true
        run: npm run coverage

      - name: archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage
          retention-days: 1

  docker:
    name: containerization
    needs: [unit-testing, code-coverage]
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: run docker
        run: |
          docker image ls
          docker run --name solar-system-app -d \
                      -p 3000:3000 \
                      -e MONGO_URI=$MONGO_URI \
                      -e MONGO_USERNAME=$MONGO_USERNAME \
                      -e MONGO_PASSWORD=$MONGO_PASSWORD \
                      ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP

          echo Testing Image URL using wget
          wget -q -O - localhost:3000/live | grep live

      - name: push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
